service: auth-server
provider:
  name: aws
  runtime: nodejs18.x
  region: eu-north-1
  timeout: 30 # by default 6s
  environment:
    CLIENT_ID: ${file(config.json):CLIENT_ID}
    CLIENT_SECRET: ${file(config.json):CLIENT_SECRET}
    CALENDAR_ID: ${file(config.json):CALENDAR_ID}

functions:
# authorization code
  getAuthURL:
    handler: handler.getAuthURL
    events:
      - http:
          path: api/get-auth-url
          method: get
# get temp access token
  getAccessToken:
    handler: handler.getAccessToken
    events:
      - http:
          path: api/token/{code}
          method: get

# use token



